#
# kubectl -n k8s-spark apply -f setup/local/volumes/local-nfs-pvc.yaml
#

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-nfs-pvc
  namespace: k8s-spark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi