#
#
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ssd-pvc
spec:
  storageClassName: ssd-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi