#
# kubectl apply -f setup/local/volumes/pod-busybox-nfs.yaml
# kubectl exec -it pod-busybox-nfs -- ls /mnt/nfs_share/nfs-dir
#

apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox-nfs
spec:
  containers:
    - image: busybox
      command:
        - sh
        - -c
        - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - mountPath: /mnt/nfs_share
          name: test-volume
  volumes:
    - name: test-volume
      nfs:
        server: 192.168.122.1
        path: /mnt/nfs_share
        readOnly: true