#
# kubectl -n k8s-spark apply -f setup/local/account/namespace.yml
#

apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: k8s-spark
  name: k8s-spark
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
