#
# kubectl apply -f setup/local/account/service-account-role.yml
# kubectl create clusterrolebinding spark-role --clusterrole=admin --serviceaccount=k8s-spark:spark --namespace=k8s-spark
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: spark
  namespace: k8s-spark
