#
# kubectl -n k8s-spark apply -f setup/local/volumes/local-storage/local-storage-sc.yaml
#
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer