#
# kubectl create secret generic az-storage-secret \
# --from-literal=azurestorageaccountname=csg100320025a786393 \
# --from-literal=azurestorageaccountkey="QjhwrUQ1gcQhebsYoIPmQONO8s2vD/rJy4NNxwMfI4zz9ENeGusZNbZFIshgxEaCJ4QRJ3VqAShD+AStXMEfrw==" \
# --dry-run=client -o yaml
#

#
# kubectl -n k8s-spark apply -f setup/aks/volumes/fileshare/az-storage-secret.yaml
# kubectl -n k8s-spark get secret az-storage-secret
#
apiVersion: v1
data:
  azurestorageaccountkey: UWpod3JVUTFnY1FoZWJzWW9JUG1RT05POHMydkQvckp5NE5OeHdNZkk0eno5RU5lR3VzWk5iWkZJc2hneEVhQ0o0UVJKM1ZxQVNoRCtBU3RYTUVmcnc9PQ==
  azurestorageaccountname: Y3NnMTAwMzIwMDI1YTc4NjM5Mw==
kind: Secret
metadata:
  creationTimestamp: null
  name: az-storage-secret
  namespace: k8s-spark