#
# kubectl -n k8s-spark apply -f setup/local/volumes/nfs/local-nfs-pv.yaml
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nfs-pv
  namespace: k8s-spark
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/nfs_share
    server: 192.168.122.1
    readOnly: false