#
# kubectl apply -f setup/local/volumes/nfs/pod-busybox-nfs.yaml
# kubectl exec -it pod-busybox-nfs -- ls /mnt/nfs_share/nfs-dir
#

apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox-nfs
spec:
  securityContext: {}
  containers:
  - image: busybox
    securityContext:
      privileged: true
    command:
      - sh
      - -c
      - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - mountPath: /mnt/nfs_share
        name: local-nfs-vol
      - mountPath: /mnt/nfs-dir
        name: nfs-volume
  volumes:
    - name: local-nfs-vol
      persistentVolumeClaim:
        claimName: "local-nfs-pvc"
    - name: nfs-volume
      nfs:
        server: 192.168.122.1
        path: /mnt/nfs_share/nfs-dir
        readOnly: true