#
# kubectl apply -f /home/brijeshdhaker/IdeaProjects/spark-on-kubernetes/setup/service-account-role.yml
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2022-12-20T02:40:33Z"
  name: spark-role
  resourceVersion: "64942"
  uid: 9f7e4c37-9709-477b-8cb0-4c5900f70c45
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: spark
  namespace: k8s-spark
