#
# kubectl apply -f /home/brijeshdhaker/IdeaProjects/kubernetes-examples/admin-dashboard/admin-user-service-account.yml
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: k8s-spark