#
# kubectl apply -f setup/local/volumes/hostpath/pod-busybox-hostpath.yaml
# kubectl exec -it pod-busybox-local-hostpath -- ls /mnt/hostpath-share
#

apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox-local-hostpath
spec:
  securityContext: {}
  containers:
  - image: busybox
    securityContext:
      privileged: true
    command:
      - sh
      - -c
      - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - name: local-hostpath-vol
        mountPath: "/mnt/hostpath-share"
  volumes:
    - name: local-hostpath-vol
      persistentVolumeClaim:
        claimName: "local-hostpath-pvc"